// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AdditionalPackageDocumentDataSlicesSlice =
  | ContentASlice
  | ContentNameSlice
  | CoverageDSlice
  | CoverageCSlice
  | CoverageBSlice
  | CoverageASlice;

/**
 * Content for Additional Package documents
 */
interface AdditionalPackageDocumentData {
  /**
   * Page Title field in *Additional Package*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: additional_package.page_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  page_title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Additional Package*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: additional_package.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AdditionalPackageDocumentDataSlicesSlice> /**
   * Meta Title field in *Additional Package*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: additional_package.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Additional Package*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: additional_package.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Additional Package*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: additional_package.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Additional Package document from Prismic
 *
 * - **API ID**: `additional_package`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AdditionalPackageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<AdditionalPackageDocumentData>,
    "additional_package",
    Lang
  >;

type ArticleDocumentDataSlicesSlice = never;

/**
 * Content for Article documents
 */
interface ArticleDocumentData {
  /**
   * Slice Zone field in *Article*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: article.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ArticleDocumentDataSlicesSlice> /**
   * Meta Title field in *Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: article.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: article.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Article*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: article.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Article document from Prismic
 *
 * - **API ID**: `article`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArticleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ArticleDocumentData>,
    "article",
    Lang
  >;

type DisclaimerDocumentDataSlicesSlice = DisclaimerSlice;

/**
 * Content for Disclaimer documents
 */
interface DisclaimerDocumentData {
  /**
   * Slice Zone field in *Disclaimer*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: disclaimer.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<DisclaimerDocumentDataSlicesSlice>;
}

/**
 * Disclaimer document from Prismic
 *
 * - **API ID**: `disclaimer`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DisclaimerDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<DisclaimerDocumentData>,
    "disclaimer",
    Lang
  >;

type HomePageDocumentDataSlicesSlice = never;

/**
 * Content for Home Page documents
 */
interface HomePageDocumentData {
  /**
   * Slice Zone field in *Home Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomePageDocumentDataSlicesSlice> /**
   * Meta Title field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home Page document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomePageDocumentData>,
    "home_page",
    Lang
  >;

type ReviewsDocumentDataSlicesSlice = ReviewsSlice;

/**
 * Content for Reviews documents
 */
interface ReviewsDocumentData {
  /**
   * Slice Zone field in *Reviews*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ReviewsDocumentDataSlicesSlice>;
}

/**
 * Reviews document from Prismic
 *
 * - **API ID**: `reviews`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ReviewsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ReviewsDocumentData>,
    "reviews",
    Lang
  >;

export type AllDocumentTypes =
  | AdditionalPackageDocument
  | ArticleDocument
  | DisclaimerDocument
  | HomePageDocument
  | ReviewsDocument;

/**
 * Primary content in *ContentA → Default → Primary*
 */
export interface ContentASliceDefaultPrimary {
  /**
   * Content field in *ContentA → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_a.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for ContentA Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentASliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContentASliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContentA*
 */
type ContentASliceVariation = ContentASliceDefault;

/**
 * ContentA Shared Slice
 *
 * - **API ID**: `content_a`
 * - **Description**: ContentA
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentASlice = prismic.SharedSlice<
  "content_a",
  ContentASliceVariation
>;

/**
 * Primary content in *ContentName → Default → Primary*
 */
export interface ContentNameSliceDefaultPrimary {
  /**
   * Text field in *ContentName → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_name.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;
}

/**
 * Default variation for ContentName Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentNameSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContentNameSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContentName*
 */
type ContentNameSliceVariation = ContentNameSliceDefault;

/**
 * ContentName Shared Slice
 *
 * - **API ID**: `content_name`
 * - **Description**: ContentName
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentNameSlice = prismic.SharedSlice<
  "content_name",
  ContentNameSliceVariation
>;

/**
 * Primary content in *CoverageA → Default → Primary*
 */
export interface CoverageASliceDefaultPrimary {
  /**
   * Coverage field in *CoverageA → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: coverage_a.default.primary.coverage
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  coverage: prismic.KeyTextField;

  /**
   * Description field in *CoverageA → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: coverage_a.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for CoverageA Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CoverageASliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CoverageASliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CoverageA*
 */
type CoverageASliceVariation = CoverageASliceDefault;

/**
 * CoverageA Shared Slice
 *
 * - **API ID**: `coverage_a`
 * - **Description**: CoverageA
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CoverageASlice = prismic.SharedSlice<
  "coverage_a",
  CoverageASliceVariation
>;

/**
 * Item in *CoverageB → Default → Primary → Packages*
 */
export interface CoverageBSliceDefaultPrimaryPackagesItem {
  /**
   * Type field in *CoverageB → Default → Primary → Packages*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: coverage_b.default.primary.packages[].type
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  type: prismic.KeyTextField;

  /**
   * Name field in *CoverageB → Default → Primary → Packages*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: coverage_b.default.primary.packages[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;
}

/**
 * Primary content in *CoverageB → Default → Primary*
 */
export interface CoverageBSliceDefaultPrimary {
  /**
   * Packages field in *CoverageB → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: coverage_b.default.primary.packages[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  packages: prismic.GroupField<
    Simplify<CoverageBSliceDefaultPrimaryPackagesItem>
  >;
}

/**
 * Default variation for CoverageB Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CoverageBSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CoverageBSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CoverageB*
 */
type CoverageBSliceVariation = CoverageBSliceDefault;

/**
 * CoverageB Shared Slice
 *
 * - **API ID**: `coverage_b`
 * - **Description**: CoverageB
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CoverageBSlice = prismic.SharedSlice<
  "coverage_b",
  CoverageBSliceVariation
>;

/**
 * Item in *CoverageC → Default → Primary → Variants*
 */
export interface CoverageCSliceDefaultPrimaryVariantsItem {
  /**
   * Variant field in *CoverageC → Default → Primary → Variants*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: coverage_c.default.primary.variants[].variant
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  variant: prismic.KeyTextField;
}

/**
 * Primary content in *CoverageC → Default → Primary*
 */
export interface CoverageCSliceDefaultPrimary {
  /**
   * Coverage field in *CoverageC → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: coverage_c.default.primary.coverage
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  coverage: prismic.KeyTextField;

  /**
   * Variants field in *CoverageC → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: coverage_c.default.primary.variants[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  variants: prismic.GroupField<
    Simplify<CoverageCSliceDefaultPrimaryVariantsItem>
  >;
}

/**
 * Default variation for CoverageC Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CoverageCSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CoverageCSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CoverageC*
 */
type CoverageCSliceVariation = CoverageCSliceDefault;

/**
 * CoverageC Shared Slice
 *
 * - **API ID**: `coverage_c`
 * - **Description**: CoverageC
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CoverageCSlice = prismic.SharedSlice<
  "coverage_c",
  CoverageCSliceVariation
>;

/**
 * Item in *CoverageD → Default → Primary → Variants*
 */
export interface CoverageDSliceDefaultPrimaryVariantsItem {
  /**
   * Variant field in *CoverageD → Default → Primary → Variants*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: coverage_d.default.primary.variants[].variant
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  variant: prismic.BooleanField;
}

/**
 * Primary content in *CoverageD → Default → Primary*
 */
export interface CoverageDSliceDefaultPrimary {
  /**
   * Coverage field in *CoverageD → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: coverage_d.default.primary.coverage
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  coverage: prismic.KeyTextField;

  /**
   * Variants field in *CoverageD → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: coverage_d.default.primary.variants[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  variants: prismic.GroupField<
    Simplify<CoverageDSliceDefaultPrimaryVariantsItem>
  >;
}

/**
 * Default variation for CoverageD Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CoverageDSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CoverageDSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CoverageD*
 */
type CoverageDSliceVariation = CoverageDSliceDefault;

/**
 * CoverageD Shared Slice
 *
 * - **API ID**: `coverage_d`
 * - **Description**: CoverageD
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CoverageDSlice = prismic.SharedSlice<
  "coverage_d",
  CoverageDSliceVariation
>;

/**
 * Primary content in *Disclaimer → Default → Primary*
 */
export interface DisclaimerSliceDefaultPrimary {
  /**
   * Title field in *Disclaimer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: disclaimer.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Disclaimer field in *Disclaimer → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: disclaimer.default.primary.disclaimer
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  disclaimer: prismic.RichTextField;
}

/**
 * Default variation for Disclaimer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DisclaimerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DisclaimerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Disclaimer*
 */
type DisclaimerSliceVariation = DisclaimerSliceDefault;

/**
 * Disclaimer Shared Slice
 *
 * - **API ID**: `disclaimer`
 * - **Description**: Disclaimer
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DisclaimerSlice = prismic.SharedSlice<
  "disclaimer",
  DisclaimerSliceVariation
>;

/**
 * Item in *Reviews → Default → Primary → Reviews*
 */
export interface ReviewsSliceDefaultPrimaryReviewsItem {
  /**
   * Image field in *Reviews → Default → Primary → Reviews*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews.default.primary.reviews[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Description field in *Reviews → Default → Primary → Reviews*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews.default.primary.reviews[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Primary content in *Reviews → Default → Primary*
 */
export interface ReviewsSliceDefaultPrimary {
  /**
   * Title field in *Reviews → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Reviews field in *Reviews → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews.default.primary.reviews[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  reviews: prismic.GroupField<Simplify<ReviewsSliceDefaultPrimaryReviewsItem>>;
}

/**
 * Default variation for Reviews Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ReviewsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ReviewsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Reviews*
 */
type ReviewsSliceVariation = ReviewsSliceDefault;

/**
 * Reviews Shared Slice
 *
 * - **API ID**: `reviews`
 * - **Description**: Reviews
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ReviewsSlice = prismic.SharedSlice<
  "reviews",
  ReviewsSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AdditionalPackageDocument,
      AdditionalPackageDocumentData,
      AdditionalPackageDocumentDataSlicesSlice,
      ArticleDocument,
      ArticleDocumentData,
      ArticleDocumentDataSlicesSlice,
      DisclaimerDocument,
      DisclaimerDocumentData,
      DisclaimerDocumentDataSlicesSlice,
      HomePageDocument,
      HomePageDocumentData,
      HomePageDocumentDataSlicesSlice,
      ReviewsDocument,
      ReviewsDocumentData,
      ReviewsDocumentDataSlicesSlice,
      AllDocumentTypes,
      ContentASlice,
      ContentASliceDefaultPrimary,
      ContentASliceVariation,
      ContentASliceDefault,
      ContentNameSlice,
      ContentNameSliceDefaultPrimary,
      ContentNameSliceVariation,
      ContentNameSliceDefault,
      CoverageASlice,
      CoverageASliceDefaultPrimary,
      CoverageASliceVariation,
      CoverageASliceDefault,
      CoverageBSlice,
      CoverageBSliceDefaultPrimaryPackagesItem,
      CoverageBSliceDefaultPrimary,
      CoverageBSliceVariation,
      CoverageBSliceDefault,
      CoverageCSlice,
      CoverageCSliceDefaultPrimaryVariantsItem,
      CoverageCSliceDefaultPrimary,
      CoverageCSliceVariation,
      CoverageCSliceDefault,
      CoverageDSlice,
      CoverageDSliceDefaultPrimaryVariantsItem,
      CoverageDSliceDefaultPrimary,
      CoverageDSliceVariation,
      CoverageDSliceDefault,
      DisclaimerSlice,
      DisclaimerSliceDefaultPrimary,
      DisclaimerSliceVariation,
      DisclaimerSliceDefault,
      ReviewsSlice,
      ReviewsSliceDefaultPrimaryReviewsItem,
      ReviewsSliceDefaultPrimary,
      ReviewsSliceVariation,
      ReviewsSliceDefault,
    };
  }
}
