// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AdditionalPackageDocumentDataSlicesSlice =
  | ContentButtonSlice
  | ContentBSlice
  | ContentASlice
  | ContentNameSlice
  | CoverageDSlice
  | CoverageCSlice
  | CoverageBSlice
  | CoverageASlice;

/**
 * Content for Additional Package documents
 */
interface AdditionalPackageDocumentData {
  /**
   * Page Title field in *Additional Package*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: additional_package.page_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  page_title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Additional Package*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: additional_package.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AdditionalPackageDocumentDataSlicesSlice> /**
   * Meta Title field in *Additional Package*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: additional_package.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Additional Package*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: additional_package.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Additional Package*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: additional_package.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Additional Package document from Prismic
 *
 * - **API ID**: `additional_package`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AdditionalPackageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<AdditionalPackageDocumentData>,
    "additional_package",
    Lang
  >;

type ArticleDocumentDataSlicesSlice = never;

/**
 * Content for Article documents
 */
interface ArticleDocumentData {
  /**
   * Slice Zone field in *Article*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: article.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ArticleDocumentDataSlicesSlice> /**
   * Meta Title field in *Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: article.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: article.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Article*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: article.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Article document from Prismic
 *
 * - **API ID**: `article`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArticleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ArticleDocumentData>,
    "article",
    Lang
  >;

/**
 * Item in *Company → FCB Telephone Numbers*
 */
export interface CompanyDocumentDataFcbTelephoneNumbersItem {
  /**
   * FCB Telephone Number field in *Company → FCB Telephone Numbers*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: company.fcb_telephone_numbers[].fcb_telephone_number
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  fcb_telephone_number: prismic.KeyTextField;
}

/**
 * Item in *Company → SCB Telephone Numbers*
 */
export interface CompanyDocumentDataScbTelephoneNumbersItem {
  /**
   * SCB Telephone Number field in *Company → SCB Telephone Numbers*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: company.scb_telephone_numbers[].scb_telephone_number
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  scb_telephone_number: prismic.KeyTextField;
}

/**
 * Content for Company documents
 */
interface CompanyDocumentData {
  /**
   * Monochrome Logo field in *Company*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: company.monochrome_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  monochrome_logo: prismic.ImageField<never>;

  /**
   * Colorful Logo field in *Company*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: company.colorful_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  colorful_logo: prismic.ImageField<never>;

  /**
   * Company Name field in *Company*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: company.company_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  company_name: prismic.KeyTextField;

  /**
   * Address field in *Company*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: company.address
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  address: prismic.KeyTextField;

  /**
   * Postcode field in *Company*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: company.postcode
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  postcode: prismic.KeyTextField;

  /**
   * Town field in *Company*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: company.town
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  town: prismic.KeyTextField;

  /**
   * Telephone Number field in *Company*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: company.telephone_number
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  telephone_number: prismic.KeyTextField;

  /**
   * Email Address field in *Company*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: company.email_address
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email_address: prismic.KeyTextField;

  /**
   * First Company Branch field in *Company*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: company.first_company_branch
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  first_company_branch: prismic.KeyTextField;

  /**
   * FCB Telephone Numbers field in *Company*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: company.fcb_telephone_numbers[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  fcb_telephone_numbers: prismic.GroupField<
    Simplify<CompanyDocumentDataFcbTelephoneNumbersItem>
  >;

  /**
   * Second Company Branch field in *Company*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: company.second_company_branch
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  second_company_branch: prismic.KeyTextField;

  /**
   * SCB Telephone Numbers field in *Company*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: company.scb_telephone_numbers[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  scb_telephone_numbers: prismic.GroupField<
    Simplify<CompanyDocumentDataScbTelephoneNumbersItem>
  >;
}

/**
 * Company document from Prismic
 *
 * - **API ID**: `company`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CompanyDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<CompanyDocumentData>,
    "company",
    Lang
  >;

type DisclaimerDocumentDataSlicesSlice = DisclaimerSlice;

/**
 * Content for Disclaimer documents
 */
interface DisclaimerDocumentData {
  /**
   * Slice Zone field in *Disclaimer*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: disclaimer.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<DisclaimerDocumentDataSlicesSlice>;
}

/**
 * Disclaimer document from Prismic
 *
 * - **API ID**: `disclaimer`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DisclaimerDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<DisclaimerDocumentData>,
    "disclaimer",
    Lang
  >;

/**
 * Item in *Footer → First Column*
 */
export interface FooterDocumentDataFirstColumnItem {
  /**
   * Link field in *Footer → First Column*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.first_column[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Label field in *Footer → First Column*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.first_column[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Item in *Footer → Second Column*
 */
export interface FooterDocumentDataSecondColumnItem {
  /**
   * Link field in *Footer → Second Column*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.second_column[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Label field in *Footer → Second Column*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.second_column[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * First Column Name field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.first_column_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  first_column_name: prismic.KeyTextField;

  /**
   * First Column field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.first_column[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  first_column: prismic.GroupField<Simplify<FooterDocumentDataFirstColumnItem>>;

  /**
   * Second Column Name field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.second_column_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  second_column_name: prismic.KeyTextField;

  /**
   * Second Column field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.second_column[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  second_column: prismic.GroupField<
    Simplify<FooterDocumentDataSecondColumnItem>
  >;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

/**
 * Item in *Header → Links*
 */
export interface HeaderDocumentDataLinksItem {
  /**
   * Label field in *Header → Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.links[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Header → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Content for Header documents
 */
interface HeaderDocumentData {
  /**
   * Links field in *Header*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: header.links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<Simplify<HeaderDocumentDataLinksItem>>;
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HeaderDocumentData>,
    "header",
    Lang
  >;

type HomePageDocumentDataSlicesSlice = never;

/**
 * Content for Home Page documents
 */
interface HomePageDocumentData {
  /**
   * Slice Zone field in *Home Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomePageDocumentDataSlicesSlice> /**
   * Meta Title field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home Page document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomePageDocumentData>,
    "home_page",
    Lang
  >;

type ReviewsDocumentDataSlicesSlice = ReviewsSlice;

/**
 * Content for Reviews documents
 */
interface ReviewsDocumentData {
  /**
   * Slice Zone field in *Reviews*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ReviewsDocumentDataSlicesSlice>;
}

/**
 * Reviews document from Prismic
 *
 * - **API ID**: `reviews`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ReviewsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ReviewsDocumentData>,
    "reviews",
    Lang
  >;

export type AllDocumentTypes =
  | AdditionalPackageDocument
  | ArticleDocument
  | CompanyDocument
  | DisclaimerDocument
  | FooterDocument
  | HeaderDocument
  | HomePageDocument
  | ReviewsDocument;

/**
 * Primary content in *ContentA → Default → Primary*
 */
export interface ContentASliceDefaultPrimary {
  /**
   * Content field in *ContentA → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_a.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for ContentA Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentASliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContentASliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContentA*
 */
type ContentASliceVariation = ContentASliceDefault;

/**
 * ContentA Shared Slice
 *
 * - **API ID**: `content_a`
 * - **Description**: ContentA
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentASlice = prismic.SharedSlice<
  "content_a",
  ContentASliceVariation
>;

/**
 * Item in *ContentB → Default → Primary → Additional informations*
 */
export interface ContentBSliceDefaultPrimaryAdditionalInformationsItem {
  /**
   * Number field in *ContentB → Default → Primary → Additional informations*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: content_b.default.primary.additional_informations[].number
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  number: prismic.NumberField;

  /**
   * Text field in *ContentB → Default → Primary → Additional informations*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_b.default.primary.additional_informations[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Primary content in *ContentB → Default → Primary*
 */
export interface ContentBSliceDefaultPrimary {
  /**
   * Additional informations field in *ContentB → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: content_b.default.primary.additional_informations[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  additional_informations: prismic.GroupField<
    Simplify<ContentBSliceDefaultPrimaryAdditionalInformationsItem>
  >;

  /**
   * Frame field in *ContentB → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_b.default.primary.frame
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  frame: prismic.RichTextField;
}

/**
 * Default variation for ContentB Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentBSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContentBSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContentB*
 */
type ContentBSliceVariation = ContentBSliceDefault;

/**
 * ContentB Shared Slice
 *
 * - **API ID**: `content_b`
 * - **Description**: ContentB
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentBSlice = prismic.SharedSlice<
  "content_b",
  ContentBSliceVariation
>;

/**
 * Primary content in *ContentButton → Default → Primary*
 */
export interface ContentButtonSliceDefaultPrimary {
  /**
   * Label field in *ContentButton → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_button.default.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Default variation for ContentButton Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentButtonSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContentButtonSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContentButton*
 */
type ContentButtonSliceVariation = ContentButtonSliceDefault;

/**
 * ContentButton Shared Slice
 *
 * - **API ID**: `content_button`
 * - **Description**: ContentButton
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentButtonSlice = prismic.SharedSlice<
  "content_button",
  ContentButtonSliceVariation
>;

/**
 * Primary content in *ContentName → Default → Primary*
 */
export interface ContentNameSliceDefaultPrimary {
  /**
   * Text field in *ContentName → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_name.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;
}

/**
 * Default variation for ContentName Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentNameSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContentNameSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContentName*
 */
type ContentNameSliceVariation = ContentNameSliceDefault;

/**
 * ContentName Shared Slice
 *
 * - **API ID**: `content_name`
 * - **Description**: ContentName
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentNameSlice = prismic.SharedSlice<
  "content_name",
  ContentNameSliceVariation
>;

/**
 * Primary content in *CoverageA → Default → Primary*
 */
export interface CoverageASliceDefaultPrimary {
  /**
   * Coverage field in *CoverageA → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: coverage_a.default.primary.coverage
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  coverage: prismic.KeyTextField;

  /**
   * Description field in *CoverageA → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: coverage_a.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for CoverageA Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CoverageASliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CoverageASliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CoverageA*
 */
type CoverageASliceVariation = CoverageASliceDefault;

/**
 * CoverageA Shared Slice
 *
 * - **API ID**: `coverage_a`
 * - **Description**: CoverageA
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CoverageASlice = prismic.SharedSlice<
  "coverage_a",
  CoverageASliceVariation
>;

/**
 * Item in *CoverageB → Default → Primary → Packages*
 */
export interface CoverageBSliceDefaultPrimaryPackagesItem {
  /**
   * Type field in *CoverageB → Default → Primary → Packages*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: coverage_b.default.primary.packages[].type
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  type: prismic.KeyTextField;

  /**
   * Name field in *CoverageB → Default → Primary → Packages*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: coverage_b.default.primary.packages[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;
}

/**
 * Primary content in *CoverageB → Default → Primary*
 */
export interface CoverageBSliceDefaultPrimary {
  /**
   * Packages field in *CoverageB → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: coverage_b.default.primary.packages[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  packages: prismic.GroupField<
    Simplify<CoverageBSliceDefaultPrimaryPackagesItem>
  >;
}

/**
 * Default variation for CoverageB Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CoverageBSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CoverageBSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CoverageB*
 */
type CoverageBSliceVariation = CoverageBSliceDefault;

/**
 * CoverageB Shared Slice
 *
 * - **API ID**: `coverage_b`
 * - **Description**: CoverageB
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CoverageBSlice = prismic.SharedSlice<
  "coverage_b",
  CoverageBSliceVariation
>;

/**
 * Item in *CoverageC → Default → Primary → Variants*
 */
export interface CoverageCSliceDefaultPrimaryVariantsItem {
  /**
   * Variant field in *CoverageC → Default → Primary → Variants*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: coverage_c.default.primary.variants[].variant
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  variant: prismic.KeyTextField;
}

/**
 * Primary content in *CoverageC → Default → Primary*
 */
export interface CoverageCSliceDefaultPrimary {
  /**
   * Coverage field in *CoverageC → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: coverage_c.default.primary.coverage
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  coverage: prismic.KeyTextField;

  /**
   * Variants field in *CoverageC → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: coverage_c.default.primary.variants[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  variants: prismic.GroupField<
    Simplify<CoverageCSliceDefaultPrimaryVariantsItem>
  >;
}

/**
 * Default variation for CoverageC Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CoverageCSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CoverageCSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CoverageC*
 */
type CoverageCSliceVariation = CoverageCSliceDefault;

/**
 * CoverageC Shared Slice
 *
 * - **API ID**: `coverage_c`
 * - **Description**: CoverageC
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CoverageCSlice = prismic.SharedSlice<
  "coverage_c",
  CoverageCSliceVariation
>;

/**
 * Item in *CoverageD → Default → Primary → Variants*
 */
export interface CoverageDSliceDefaultPrimaryVariantsItem {
  /**
   * Variant field in *CoverageD → Default → Primary → Variants*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: coverage_d.default.primary.variants[].variant
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  variant: prismic.BooleanField;
}

/**
 * Primary content in *CoverageD → Default → Primary*
 */
export interface CoverageDSliceDefaultPrimary {
  /**
   * Coverage field in *CoverageD → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: coverage_d.default.primary.coverage
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  coverage: prismic.KeyTextField;

  /**
   * Variants field in *CoverageD → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: coverage_d.default.primary.variants[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  variants: prismic.GroupField<
    Simplify<CoverageDSliceDefaultPrimaryVariantsItem>
  >;
}

/**
 * Default variation for CoverageD Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CoverageDSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CoverageDSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CoverageD*
 */
type CoverageDSliceVariation = CoverageDSliceDefault;

/**
 * CoverageD Shared Slice
 *
 * - **API ID**: `coverage_d`
 * - **Description**: CoverageD
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CoverageDSlice = prismic.SharedSlice<
  "coverage_d",
  CoverageDSliceVariation
>;

/**
 * Primary content in *Disclaimer → Default → Primary*
 */
export interface DisclaimerSliceDefaultPrimary {
  /**
   * Title field in *Disclaimer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: disclaimer.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Disclaimer field in *Disclaimer → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: disclaimer.default.primary.disclaimer
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  disclaimer: prismic.RichTextField;
}

/**
 * Default variation for Disclaimer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DisclaimerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DisclaimerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Disclaimer*
 */
type DisclaimerSliceVariation = DisclaimerSliceDefault;

/**
 * Disclaimer Shared Slice
 *
 * - **API ID**: `disclaimer`
 * - **Description**: Disclaimer
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DisclaimerSlice = prismic.SharedSlice<
  "disclaimer",
  DisclaimerSliceVariation
>;

/**
 * Item in *Reviews → Default → Primary → Reviews*
 */
export interface ReviewsSliceDefaultPrimaryReviewsItem {
  /**
   * Image field in *Reviews → Default → Primary → Reviews*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews.default.primary.reviews[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Description field in *Reviews → Default → Primary → Reviews*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews.default.primary.reviews[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Primary content in *Reviews → Default → Primary*
 */
export interface ReviewsSliceDefaultPrimary {
  /**
   * Title field in *Reviews → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Reviews field in *Reviews → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews.default.primary.reviews[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  reviews: prismic.GroupField<Simplify<ReviewsSliceDefaultPrimaryReviewsItem>>;
}

/**
 * Default variation for Reviews Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ReviewsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ReviewsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Reviews*
 */
type ReviewsSliceVariation = ReviewsSliceDefault;

/**
 * Reviews Shared Slice
 *
 * - **API ID**: `reviews`
 * - **Description**: Reviews
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ReviewsSlice = prismic.SharedSlice<
  "reviews",
  ReviewsSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AdditionalPackageDocument,
      AdditionalPackageDocumentData,
      AdditionalPackageDocumentDataSlicesSlice,
      ArticleDocument,
      ArticleDocumentData,
      ArticleDocumentDataSlicesSlice,
      CompanyDocument,
      CompanyDocumentData,
      CompanyDocumentDataFcbTelephoneNumbersItem,
      CompanyDocumentDataScbTelephoneNumbersItem,
      DisclaimerDocument,
      DisclaimerDocumentData,
      DisclaimerDocumentDataSlicesSlice,
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataFirstColumnItem,
      FooterDocumentDataSecondColumnItem,
      HeaderDocument,
      HeaderDocumentData,
      HeaderDocumentDataLinksItem,
      HomePageDocument,
      HomePageDocumentData,
      HomePageDocumentDataSlicesSlice,
      ReviewsDocument,
      ReviewsDocumentData,
      ReviewsDocumentDataSlicesSlice,
      AllDocumentTypes,
      ContentASlice,
      ContentASliceDefaultPrimary,
      ContentASliceVariation,
      ContentASliceDefault,
      ContentBSlice,
      ContentBSliceDefaultPrimaryAdditionalInformationsItem,
      ContentBSliceDefaultPrimary,
      ContentBSliceVariation,
      ContentBSliceDefault,
      ContentButtonSlice,
      ContentButtonSliceDefaultPrimary,
      ContentButtonSliceVariation,
      ContentButtonSliceDefault,
      ContentNameSlice,
      ContentNameSliceDefaultPrimary,
      ContentNameSliceVariation,
      ContentNameSliceDefault,
      CoverageASlice,
      CoverageASliceDefaultPrimary,
      CoverageASliceVariation,
      CoverageASliceDefault,
      CoverageBSlice,
      CoverageBSliceDefaultPrimaryPackagesItem,
      CoverageBSliceDefaultPrimary,
      CoverageBSliceVariation,
      CoverageBSliceDefault,
      CoverageCSlice,
      CoverageCSliceDefaultPrimaryVariantsItem,
      CoverageCSliceDefaultPrimary,
      CoverageCSliceVariation,
      CoverageCSliceDefault,
      CoverageDSlice,
      CoverageDSliceDefaultPrimaryVariantsItem,
      CoverageDSliceDefaultPrimary,
      CoverageDSliceVariation,
      CoverageDSliceDefault,
      DisclaimerSlice,
      DisclaimerSliceDefaultPrimary,
      DisclaimerSliceVariation,
      DisclaimerSliceDefault,
      ReviewsSlice,
      ReviewsSliceDefaultPrimaryReviewsItem,
      ReviewsSliceDefaultPrimary,
      ReviewsSliceVariation,
      ReviewsSliceDefault,
    };
  }
}
