// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  content_a: defineAsyncComponent(() => import("./ContentA/index.vue")),
  content_name: defineAsyncComponent(() => import("./ContentName/index.vue")),
  coverage_a: defineAsyncComponent(() => import("./CoverageA/index.vue")),
  coverage_b: defineAsyncComponent(() => import("./CoverageB/index.vue")),
  coverage_c: defineAsyncComponent(() => import("./CoverageC/index.vue")),
  coverage_d: defineAsyncComponent(() => import("./CoverageD/index.vue")),
  disclaimer: defineAsyncComponent(() => import("./Disclaimer/index.vue")),
  reviews: defineAsyncComponent(() => import("./Reviews/index.vue")),
});
